version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: seop_db
    ports:
      - "5432:5432" # Porta do PC : Porta do Container
    environment:
      - POSTGRES_USER=seop_user
      - POSTGRES_PASSWORD=seop_password
      - POSTGRES_DB=seop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: